# Generated by Django 4.2 on 2023-10-06 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
